### ISSUE TITLE
"Lift does not have any fuel"

### ISSUE THREAD

**Issue by S1mpleM0use** [lucaargolo/lifts#12]
Here's the link for the video that describes the issue:
https://www.youtube.com/watch?v=x7MjByCWXHc

**Comment by lucaargolo** [comment]
Well, I don't see what's wrong with your video... 
Stirling Lifts need 100 stored ticks per block traveled, so initially, you didn't have enough stored energy to activate the lifts (that's why it was saying not enough fuel, and the redstone signal was not working). 
Then after some time have passed, and more coal had burned, the lift finally had enough energy and you successfully activated it and consumed the stored energy. After that, you tried activating the lift again but it obviously didn't work since you spent all its energy activating it previously. So it stopped working and you had to wait for it to burn more fuel. 
If you think the stirling lift is taking too long to burn enough fuel you can always change how many stored ticks are needed per block in the mod's config file, but I strongly recommend using the electric variants.

**Comment by S1mpleM0use** [comment]
thanks, didn't know about this
